### ISSUE TITLE
Having already a db running

### ISSUE THREAD

**Issue by MahmoudAbdo90** [Cvmcosta/ltijs-postgres#3]
Hello @Cvmcosta  , 
I was walking through implementing this code into our project but I can not see clearly what is going to happen in the db, and if I have a db that running, I would like to add the changes to it without having a new one. 
I am not sure if I can get an explanation here ? 
if someone can help that would be appreciated.

**Comment by Cvmcosta** [comment]
Hello @MahmoudAbdo90, You can connect to an already existing db, just pass the credentials and address to the constructor. Ltijs won't mess with already existing information in your database, it will only create the new tables.

**Comment by MahmoudAbdo90** [comment]
@Cvmcosta The thing is, there might be conflict or repeated data that's why I am asking, 
is the whole code is here in this Repo ?

**Comment by MahmoudAbdo90** [comment]
@Cvmcosta  I am still on the way to get it working, but do you have an idea when you configure the developer key in Canvas to which url you refer the JWK method when you are using Ltijs ?

**Comment by Cvmcosta** [comment]
@MahmoudAbdo90 At the moment ltijs does not have a keyset endpoint. I'll be implementing it until the end of the week. Until then you can convert the public rsa key that ltijs gives you to JWK and set it on Canvas. You can convert it [here](https://8gwifi.org/jwkconvertfunctions.jsp).

**Comment by MahmoudAbdo90** [comment]
@Cvmcosta if you have a code sample implementing it with canvas that would be great

**Comment by Cvmcosta** [comment]
@MahmoudAbdo90  I wrote a tutorial on medium and the code for the sample application is [here](https://github.com/Cvmcosta/ltijs-examples/tree/master/lti-provider). 

The code would be the same for Canvas except for the platform registration that would be something like this :
```
 let plat = await lti.registerPlatform({ 
    url: 'https://canvas.instructure.com',
    name: 'Platform Name',
    clientId: 'TOOLCLIENTID',
    authenticationEndpoint: 'https://canvas.instructure.com/api/lti/authorization_redirect',
    accesstokenEndpoint: 'https://canvas.instructure.com/login/oauth2/token',
    authConfig: { method: 'JWK_SET', key: 'https://canvas.instructure.com/api/lti/security/jwks' }
})
```
I've referenced some useful tutorial links [here](https://github.com/omsmith/ims-lti/issues/82#issuecomment-564542151).

 Furthermore i'm working on a version of the Moodle tutorial for Canvas with a more detailed step-by-step.

**Comment by MahmoudAbdo90** [comment]
Okay, once you have it let me know please.

Thanks for your help
