### ISSUE TITLE
yarn add ltijs-postgres 

### ISSUE THREAD

**Issue by MahmoudAbdo90** [Cvmcosta/ltijs-postgres#4]
Hello, 
Whenever I am trying yarn add ltijs-postgres 
it throws this error  (No valid versions found for "ltijs-postgres". The package may be unpublished).

**Comment by Cvmcosta** [comment]
I just realized that the documentation is wrong. Jesus, I'm sorry. The correct package name is ltijs-postgresql, I updated it and forgot to change the docs.
